from .estimation import (
    RegressionEstimate,
    ScaleConsistencyTestResult,
    SplitScaleConsistencyTestResult,
    feasible_precision_weights,
    feasible_wls,
    oracle_precision_weights,
    oracle_wls,
    pilot_ols,
    residual_statistic,
    run_split_scale_consistency_test,
    run_scale_consistency_test,
    weighted_least_squares,
)
from .experiments import (
    BoundaryPowerConfig,
    BoundaryPowerRow,
    FWLSOracleConfig,
    FWLSOracleRow,
    MisspecificationConfig,
    MisspecificationRow,
    NoiseRobustnessConfig,
    NoiseRobustnessRow,
    NullCalibrationConfig,
    NullCalibrationRow,
    RateConstantConfig,
    RateConstantRow,
    Sigma0PluginConfig,
    Sigma0PluginRow,
    run_boundary_power_experiment,
    run_fwls_oracle_experiment,
    run_misspecification_experiment,
    run_noise_robustness_experiment,
    run_null_calibration_experiment,
    run_rate_constant_experiment,
    run_sigma0_plugin_experiment,
)
from .model import (
    exact_scale_profile,
    log_scale_signal,
    log_variance_profile,
    misspecified_scale_profile,
    simulate_log_observations,
    simulate_observed_discrepancies,
)
from .report import export_rows_csv, generate_v1_reports, write_latex_table
from .theory_diagnostics import (
    chi_square_degrees_of_freedom,
    chi_square_null_mean,
    chi_square_null_variance,
    information_scale,
    kappa_boundary,
    lag_energy,
    oracle_h_variance,
    scaled_rmse_constant,
)

__all__ = [
    "BoundaryPowerConfig",
    "BoundaryPowerRow",
    "FWLSOracleConfig",
    "FWLSOracleRow",
    "MisspecificationConfig",
    "MisspecificationRow",
    "NoiseRobustnessConfig",
    "NoiseRobustnessRow",
    "NullCalibrationConfig",
    "NullCalibrationRow",
    "RateConstantConfig",
    "RateConstantRow",
    "Sigma0PluginConfig",
    "Sigma0PluginRow",
    "RegressionEstimate",
    "ScaleConsistencyTestResult",
    "SplitScaleConsistencyTestResult",
    "chi_square_degrees_of_freedom",
    "chi_square_null_mean",
    "chi_square_null_variance",
    "exact_scale_profile",
    "feasible_precision_weights",
    "feasible_wls",
    "generate_v1_figures",
    "generate_v1_reports",
    "information_scale",
    "kappa_boundary",
    "lag_energy",
    "log_scale_signal",
    "log_variance_profile",
    "misspecified_scale_profile",
    "oracle_h_variance",
    "oracle_precision_weights",
    "oracle_wls",
    "pilot_ols",
    "residual_statistic",
    "run_boundary_power_experiment",
    "run_fwls_oracle_experiment",
    "run_misspecification_experiment",
    "run_noise_robustness_experiment",
    "run_null_calibration_experiment",
    "run_rate_constant_experiment",
    "run_sigma0_plugin_experiment",
    "run_scale_consistency_test",
    "run_split_scale_consistency_test",
    "scaled_rmse_constant",
    "simulate_log_observations",
    "simulate_observed_discrepancies",
    "export_rows_csv",
    "write_latex_table",
    "weighted_least_squares",
]


def generate_v1_figures(*args, **kwargs):
    from .plots import generate_v1_figures as _generate_v1_figures

    return _generate_v1_figures(*args, **kwargs)
